### ISSUE TITLE
Only works for .Net 4.5.2 or greater

### ISSUE THREAD

**Issue by Micha-kun** [structurizr/dotnet#1]
I'm trying to use it un a project using .NET 4.5 and it fails because it forcefully requires at least .NET 4.5.2. Can you downgrade the framework? Thank you.

**Comment by simonbrowndotje** [comment]
I'm not sure it's possible I'm afraid, the "Microsoft.CodeAnalysis.Workspaces.Desktop" assembly (which is a part of Roslyn) has a dependency on .NET 4.5.2 for some reason. I've downgraded the target framework to 4.5, reinstalled the dependencies via NuGet and the solution won't rebuild because of the following (see attached). Any thoughts?
<img width="552" alt="screen shot 2016-04-19 at 16 43 38" src="https://cloud.githubusercontent.com/assets/1009874/14645739/c7f7ef0a-064e-11e6-8cf8-ff0b6fcd9fa7.png">

**Comment by Micha-kun** [comment]
Hmmm when you use this package? Structurizr.Core only requires Json.Net, not that package.

**Comment by Micha-kun** [comment]
Wait a moment... why are you using .net core packages for a non-.net core library? (Like System.IO package)

**Comment by simonbrowndotje** [comment]
I'm not sure where System.IO came from ... I've removed all references and re-added the necessary dependencies (Json.Net and Roslyn ... all of the other System.* stuff seems to be pulled in by Roslyn). I still can't get the solution to compile when targeting .NET 4.5 though.

**Comment by toddmeinershagen** [comment]
Do you require Roslyn for this?

**Comment by simonbrowndotje** [comment]
Roslyn is used to parse the source code and grab the summary level comment -> https://github.com/structurizr/dotnet/blob/master/Structurizr.Core/Analysis/TypeSummaryComponentFinderStrategy.cs

Is there an alternative way to do this? Or I should I simply split this out from the core library?

**Comment by Micha-kun** [comment]
It's really necessary that functionality?

**Comment by simonbrowndotje** [comment]
No, it's not "necessary". I'll split out the Roslyn stuff into a separate project, and therefore a separate NuGet package. :-)
