### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by JohnnyShep** [structurizr/dotnet#12]
Hi is there any plans with the .Net version to allow custom attributes to be added to classes so that they can be read e.g "Description", "Technology", "Uses". or have I just missed something

**Comment by coldacid** [comment]
@JohnnyShep the Cecil based analyzer I've been working on can pick out attributed classes as components, but it doesn't take into account any properties or constructor parameters of the attribute since it's meant to be generic (i.e. it just matches types with a given attribute on it).

If you want to match particular attributes and set properties and relationships of your workspace model's elements from them, at least for now you'll need to write your own `ComponentFinderStrategy` class to do the work. The type matchers for the Reflection based analyzer and my Cecil based analyzer don't support per-type "Description" or "Technology", and nothing in place right now handles adding relationships during the component finding process.

**Comment by simonbrowndotje** [comment]
I also need to port this (https://github.com/structurizr/java/blob/master/docs/structurizr-annotations.md) across from the Java version of the client library ... it's pretty much the last thing missing from the .NET version.
