### ISSUE TITLE
Structurizr API fails to load json which structurizr JsonReader loads correctly

### ISSUE THREAD

**Issue by alexey-aurea** [structurizr/dotnet#72]
Hi,

I have a json file which i can successfully create a workspace from (using the Structurizr API), but I am not able to upload it to the Structurizr workspace online. Do you have any idea how to fix it ? The file has a full model of my product so Id rather not share it in the public access.

**Comment by simonbrowndotje** [comment]
There are some errors in the server logs related to containers not having a name, so that's worth checking ... although the .NET client library should be preventing this from happening. Otherwise, I'd export the JSON from the .NET client library, and load it with the Java client library (this is used on the server, so you'll likely see the same error). A Java program like this should do the trick:

```
import com.structurizr.util.WorkspaceUtils;

import java.io.File;

public class LoadWorkspace {

    public static void main(String[] args) throws Exception {
        WorkspaceUtils.loadWorkspaceFromJson(new File("myworkspace.json"));
    }

}
```

The [Structurizr CLI](https://github.com/structurizr/cli/blob/master/docs/export.md) may also show you the same error, for example if you try to export the JSON to PlantUML format:

```
java -jar structurizr-cli-*.jar export -workspace myworkspace.json -format plantuml
```
