### ISSUE TITLE
Can't remove elements from model

### ISSUE THREAD

**Issue by sschutten** [structurizr/dotnet#87]
Perhaps it's my own lack of knowledge of the SDK or the use of `HashSet<type>`, but I can't seem to be able to remove elements from the model.

I'm using `Structurizr.Client` `v1.0.0` with `Structurizr.Core` `v1.0.0`.

``` csharp
workspace.Model.DeploymentNodes.Count;
// result: 10

workspace.Model.DeploymentNodes.Clear();
workspace.Model.DeploymentNodes.Count;
// result: 10
// expected: 0
```

The weird thing is that if I assign the set to a separate variable, I can clear that variable, but the model remains untouched.
``` csharp
workspace.Model.DeploymentNodes.Count;
// result: 10

var nodes = workspace.Model.DeploymentNodes;
nodes.Clear();
nodes.Count;
// result: 0
workspace.Model.DeploymentNodes.Count;
// result: 10
// expected: 0
```

This really confuses the heck out of me 😵

**Comment by sschutten** [comment]
I've been inspecting the code and notice that a new `HashSet` is returned based on the private `HashSet`. Here's the property:
https://github.com/structurizr/dotnet/blob/8430852d0dee3f07d5596fa10cde211655c20cdf/Structurizr.Core/Model/Model.cs#L56-L67

That explains why I can't delete anything from the `HashSet`, as it's a copy. If this is intentionally and by design, what would be the correct approach for removing elements from the model?

**Comment by simonbrowndotje** [comment]
> If this is intentionally and by design, what would be the correct approach for removing elements from the model?

It is, the library is designed to be append-only and immutable - there's no way to remove items from the model once they've been added. If you want to use the library in that way, I'd probably recommend creating a fork, and changing those lines of code to not return copies. If you do this, you'll need to ensure the following happens when you remove a deployment node from the model:

- remove children (infrastructure nodes, software system/container instances, and any deployment nodes)
- remove relationships between the above
- remove references to those removed items from any views
- etc

**Comment by sschutten** [comment]
OK, thank you for the insight and quick reply. It makes sense to have it be immutable. I've to think about what to do when our architecture change, especially if we remove containers from our solution. For the time being we refresh the workspace using the dsl tool and append the rest through code. That makes for a decent solution moving forward.
